### ISSUE TITLE
faster rcnn on ActionGenome

### ISSUE THREAD

**Issue by tyshiwo1** [JingweiJ/ActionGenome#9]
Aftering training on AG, I found that mAP of faster rcnn with Res101 is quite low. Is this my own problem or the dataset's?

**Comment by yrcong** [comment]
Hi,
what mAP have you got? My trained model performs about 25 (IOU 0.5)

**Comment by tyshiwo1** [comment]
Thank you. I found a bug in my code yesterday. Faster rcnn mAP is about 25.13 now.
















At 2020-09-14 18:27:57, "Yuren Cong" <notifications@github.com> wrote:

Hi,
what mAP have you got? My trained model performs about 25 (IOU 0.5)

**Comment by yrcong** [comment]
I think we are talking about IoU=0.5? But 25 is still quite low. May i ask which fasterRcnn Code you are using? I am using the code from Yang https://github.com/jwyang/faster-rcnn.pytorch. My colleague told me his code performs bad on COCO and VG (don't know why).

________________________________
发件人: tyshiwo1 <notifications@github.com>
发送时间: 2020年9月15日 8:44
收件人: JingweiJ/ActionGenome <ActionGenome@noreply.github.com>
抄送: Yuren Cong <congyuren@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [JingweiJ/ActionGenome] faster rcnn on ActionGenome (#9)


Thank you. I found a bug in my code yesterday. Faster rcnn mAP is about 25.13 now.
















At 2020-09-14 18:27:57, "Yuren Cong" <notifications@github.com> wrote:

Hi,
what mAP have you got? My trained model performs about 25 (IOU 0.5)

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―
